"""empty message

Revision ID: 20f51de281fe
Revises: d9b2e624ba73
Create Date: 2022-11-29 14:19:40.440006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f51de281fe'
down_revision = 'd9b2e624ba73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientfirstname', sa.String(length=80), nullable=False),
    sa.Column('patientlastname', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('medicalnote', sa.String(), nullable=False),
    sa.Column('diagnosisstatus', sa.String(length=80), nullable=False),
    sa.Column('doctorusername', sa.String(length=80), nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctorid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_user_doctorid'), ['doctorid'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_doctorid'), type_='unique')
        batch_op.drop_column('department')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')
        batch_op.drop_column('level')
        batch_op.drop_column('address')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('doctorid')

    op.drop_table('patients')
    # ### end Alembic commands ###
