"""empty message

Revision ID: 23c6976ebc56
Revises: f2b7bef28d57
Create Date: 2022-11-29 12:53:06.932671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c6976ebc56'
down_revision = 'f2b7bef28d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiredate', sa.Date(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_user_doctorid'), ['doctorid'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_doctorid'), type_='unique')
        batch_op.drop_column('hiredate')

    # ### end Alembic commands ###
