"""empty message

Revision ID: 24b80ed4fcdc
Revises: 187b8e236ffe
Create Date: 2022-12-02 12:51:22.471501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b80ed4fcdc'
down_revision = '187b8e236ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_patients')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rowid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('patientid', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_patients_patientid'), ['patientid'])
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rowid', sa.Integer(), nullable=False))
        batch_op.alter_column('doctorid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('hiredate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiredate', sa.DATE(), nullable=True))
        batch_op.alter_column('doctorid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('rowid')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_patients_patientid'), type_='unique')
        batch_op.drop_column('patientid')
        batch_op.drop_column('rowid')

    op.create_table('_alembic_tmp_patients',
    sa.Column('patientfirstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('patientlastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=80), nullable=False),
    sa.Column('status', sa.VARCHAR(length=80), nullable=False),
    sa.Column('medicalnote', sa.VARCHAR(), nullable=False),
    sa.Column('diagnosisstatus', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorusername', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorid', sa.INTEGER(), nullable=False),
    sa.Column('rowid', sa.INTEGER(), nullable=False),
    sa.Column('patientid', sa.INTEGER(), nullable=True),
    sa.UniqueConstraint('patientid', name='uq_patients_patientid'),
    sa.UniqueConstraint('rowid', name='uq_patients_rowid')
    )
    # ### end Alembic commands ###
