"""empty message

Revision ID: 2b4db2728072
Revises: c021e98e767f
Create Date: 2023-02-25 11:33:34.272147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4db2728072'
down_revision = 'c021e98e767f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_status', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
