"""updated user(doctor) table and new patient's table

Revision ID: 4a2012952ef2
Revises: 450a6b32471b
Create Date: 2022-11-29 12:29:54.229121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2012952ef2'
down_revision = '450a6b32471b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientfirstname', sa.String(length=80), nullable=False),
    sa.Column('patientlastname', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('medicalnote', sa.String(), nullable=False),
    sa.Column('diagnosisstatus', sa.String(length=80), nullable=False),
    sa.Column('doctorusername', sa.String(length=80), nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False, foreign_key=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiredate', sa.Date(), nullable=False))
        batch_op.create_unique_constraint(None, ['doctorid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('hiredate')

    op.drop_table('patients')
    # ### end Alembic commands ###
