"""empty message

Revision ID: 5ef8d2db21da
Revises: 5ee665793392
Create Date: 2022-12-02 15:49:04.216888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef8d2db21da'
down_revision = '5ee665793392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_patients')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctorfirstname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('doctorlastname', sa.String(length=80), nullable=False))
        batch_op.alter_column('patientid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('uq_patients_patientid', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_patients_id'), ['id'])
        batch_op.drop_column('doctorusername')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctorusername', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_patients_id'), type_='unique')
        batch_op.create_unique_constraint('uq_patients_patientid', ['patientid'])
        batch_op.alter_column('patientid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('doctorlastname')
        batch_op.drop_column('doctorfirstname')

    op.create_table('_alembic_tmp_patients',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('patientfirstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('patientlastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=80), nullable=False),
    sa.Column('status', sa.VARCHAR(length=80), nullable=False),
    sa.Column('medicalnote', sa.VARCHAR(), nullable=False),
    sa.Column('diagnosisstatus', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorid', sa.INTEGER(), nullable=False),
    sa.Column('patientid', sa.INTEGER(), nullable=True),
    sa.Column('doctorfirstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorlastname', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_patients_id')
    )
    # ### end Alembic commands ###
