"""empty message

Revision ID: 75f19c1179d0
Revises: 93150fc2eca5
Create Date: 2023-02-25 14:48:54.003063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f19c1179d0'
down_revision = '93150fc2eca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DoctorStatus',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('doctorid', sa.Integer(), nullable=True),
    sa.Column('doctorfirstname', sa.String(length=80), nullable=False),
    sa.Column('doctorlastname', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('doctorusername', sa.String(length=80), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['doctorid'], ['user.doctorid'], name=op.f('fk_DoctorStatus_doctorid_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_DoctorStatus')),
    sa.UniqueConstraint('id', name=op.f('uq_DoctorStatus_id'))
    )
    op.drop_table('doctor_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_status',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('doctorid', sa.INTEGER(), nullable=True),
    sa.Column('doctorfirstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorlastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('status', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorusername', sa.VARCHAR(length=80), nullable=True),
    sa.Column('date', sa.VARCHAR(length=80), nullable=True),
    sa.Column('department', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_doctor_status'),
    sa.UniqueConstraint('id', name='uq_doctor_status_id')
    )
    op.drop_table('DoctorStatus')
    # ### end Alembic commands ###
