"""empty message

Revision ID: 80d4dfa46f7b
Revises: cfd93f0a0146
Create Date: 2023-02-24 14:44:29.553320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d4dfa46f7b'
down_revision = 'cfd93f0a0146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
