"""empty message

Revision ID: b621e0ab46ec
Revises: b3de114d299f
Create Date: 2022-12-07 11:43:02.507952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b621e0ab46ec'
down_revision = 'b3de114d299f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currentdepartment', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('currentdepartment')

    # ### end Alembic commands ###
