"""empty message

Revision ID: cfd93f0a0146
Revises: 29d8152a9b93
Create Date: 2022-12-09 19:45:31.775722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd93f0a0146'
down_revision = '29d8152a9b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=80),
               existing_nullable=True)

    with op.batch_alter_table('referral_history', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_history', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=80),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=80),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
