"""empty message

Revision ID: d2131ca535f8
Revises: b621e0ab46ec
Create Date: 2022-12-08 21:51:07.062740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2131ca535f8'
down_revision = 'b621e0ab46ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patientid', sa.Integer(), nullable=False),
    sa.Column('patientfirstname', sa.String(length=80), nullable=False),
    sa.Column('patientlastname', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('currentdepartment', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('medicalnote', sa.String(), nullable=False),
    sa.Column('diagnosisstatus', sa.String(length=80), nullable=False),
    sa.Column('doctorfirstname', sa.String(length=80), nullable=False),
    sa.Column('doctorlastname', sa.String(length=80), nullable=False),
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('doctorusername', sa.String(length=80), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_history')),
    sa.UniqueConstraint('id', name=op.f('uq_referral_history_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_history')
    # ### end Alembic commands ###
