"""empty message

Revision ID: da70e422753b
Revises: 26c949a8de36
Create Date: 2022-12-02 12:18:40.230439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da70e422753b'
down_revision = '26c949a8de36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_patients')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patientid', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hiredate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiredate', sa.DATE(), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('patientid')

    op.create_table('_alembic_tmp_patients',
    sa.Column('patientfirstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('patientlastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=80), nullable=False),
    sa.Column('status', sa.VARCHAR(length=80), nullable=False),
    sa.Column('medicalnote', sa.VARCHAR(), nullable=False),
    sa.Column('diagnosisstatus', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorusername', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorid', sa.INTEGER(), nullable=False),
    sa.Column('patientid', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
