"""empty message

Revision ID: de625319d989
Revises: 23c6976ebc56
Create Date: 2022-11-29 12:57:16.767259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de625319d989'
down_revision = '23c6976ebc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiredate', sa.Date(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_user_doctorid'), ['doctorid'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_doctorid'), type_='unique')
        batch_op.drop_column('hiredate')

    op.create_table('_alembic_tmp_user',
    sa.Column('doctorid', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=False),
    sa.Column('level', sa.VARCHAR(length=80), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('hiredate', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('doctorid'),
    sa.UniqueConstraint('doctorid', name='uq_user_doctorid'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    # ### end Alembic commands ###
