"""empty message

Revision ID: 5128d28d9bfc
Revises: 3ebe44d48366
Create Date: 2022-12-02 15:44:55.079576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5128d28d9bfc'
down_revision = '3ebe44d48366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctorfirstname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('doctorlastname', sa.String(length=80), nullable=False))
        batch_op.alter_column('patientid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('uq_patients_patientid', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_patients_id'), ['id'])
        batch_op.drop_column('doctorusername')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctorusername', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_patients_id'), type_='unique')
        batch_op.create_unique_constraint('uq_patients_patientid', ['patientid'])
        batch_op.alter_column('patientid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('doctorlastname')
        batch_op.drop_column('doctorfirstname')

    # ### end Alembic commands ###
