"""empty message

Revision ID: 93150fc2eca5
Revises: 2b4db2728072
Create Date: 2023-02-25 14:46:28.121054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93150fc2eca5'
down_revision = '2b4db2728072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('age', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('doctorid', name=op.f('pk_User')),
    sa.UniqueConstraint('doctorid', name=op.f('uq_User_doctorid')),
    sa.UniqueConstraint('email', name=op.f('uq_User_email')),
    sa.UniqueConstraint('username', name=op.f('uq_User_username'))
    )
    op.create_table('DoctorStatus',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('doctorid', sa.Integer(), nullable=True),
    sa.Column('doctorfirstname', sa.String(length=80), nullable=False),
    sa.Column('doctorlastname', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('doctorusername', sa.String(length=80), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['doctorid'], ['User.doctorid'], name=op.f('fk_DoctorStatus_doctorid_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_DoctorStatus')),
    sa.UniqueConstraint('id', name=op.f('uq_DoctorStatus_id'))
    )
    op.drop_table('doctor_status')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('doctorid', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=False),
    sa.Column('level', sa.VARCHAR(length=80), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.VARCHAR(length=80), nullable=False),
    sa.Column('department', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('doctorid', name='pk_user'),
    sa.UniqueConstraint('doctorid', name='uq_user_doctorid'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('doctor_status',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('doctorid', sa.INTEGER(), nullable=True),
    sa.Column('doctorfirstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorlastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('status', sa.VARCHAR(length=80), nullable=False),
    sa.Column('doctorusername', sa.VARCHAR(length=80), nullable=True),
    sa.Column('date', sa.VARCHAR(length=80), nullable=True),
    sa.Column('department', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_doctor_status'),
    sa.UniqueConstraint('id', name='uq_doctor_status_id')
    )
    op.drop_table('DoctorStatus')
    op.drop_table('User')
    # ### end Alembic commands ###
