"""empty message

Revision ID: f2b7bef28d57
Revises: 4a2012952ef2
Create Date: 2022-11-29 12:48:18.783186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b7bef28d57'
down_revision = '4a2012952ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiredate', sa.Date(), nullable=False))
        batch_op.create_unique_constraint(None, ['doctorid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('hiredate')

    # ### end Alembic commands ###
